---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.90.60
            forwarded_port:
                BBQQ5Y9qR0qB:
                    host: '80'
                    guest: '80'
                ENvpQB3IBSxx:
                    host: '8000'
                    guest: '8000'
                #n1Fjgm1Ims55:
                    #host: '21'
                    #guest: '21'
                #VC6PzPZ6HZJa:
                    #host: '3306'
                    #guest: '3306'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            xHGC301GcabY:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - curl
        - build-essential
        - g++
        - make
        #- mysql-server
        - nodejs
        - npm
        #- tar
        #- unzip
        #- vsftpd
        - wget
firewall:
    install: '1'
    rules: null
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules: {  }
    vhosts:
        A5iIxqxh52eK:
            servername: ''
            docroot: ''
            port: ''
            engine: ''
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        C2RULdi0XkKN:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '0'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php: {  }
        pear: {  }
        pecl: {  }
    ini: {  }
    timezone: America/Vancouver
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings: {  }
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        gnjT58OYOgwO:
            version: ''
nodejs:
    install: '1'
    npm_packages:
        #- bcrypt-nodejs
        #- body-parser
        #- bower
        #- coffee-script
        #- connect-assets
        #- cookie-parser
        #- cron
        #- debug
        - ejs
        - express
        #- express-generator
        #- forever
        - grunt
        - grunt-cli
        - grunt-contrib-clean
        - grunt-contrib-coffee
        - grunt-contrib-concat
        - grunt-contrib-copy
        - grunt-contrib-cssmin
        #- grunt-contrib-jade
        #- grunt-contrib-jasmine        
        - grunt-contrib-jst
        - grunt-contrib-less
        - grunt-contrib-uglify
        #- grunt-contrib-stylus
        - grunt-contrib-watch
        - grunt-forever        
        #- grunt-protractor-runner
        - grunt-sails-linker
        - grunt-sync
        - include-all
        #- jade
        #- jwt-simple
        #- karma
        #- karma-jasmine
        - lodash
        #- moment
        #- morgan
        #- mysql
        #- node-inspector
        #- nodemon
        #- passport
        #- passport-http
        #- protractor
        - rc
        #- redis        
        - sails
        - sails-disk
        #- sails-config
        #- sails-generate
        #- sails-mongo
        #- sails-mysql
        #- sails-redis
        - serve-favicon
        #- socket.io
        #- stylus
        - yelp
python:
    install: '1'
    packages: {  }
    versions:
        xCJr1rnvkUa5:
            version: ''
mysql:
    install: '1'
    root_password: tester
    adminer: 0
    databases:
        KfZQe84nWE7P:
            grant:
                - ALL
            name: sqldb1
            host: localhost
            user: sqluser1
            password: tester
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

